/*
 * Address Service RESTful API
 *
 * This is the RESTful API for the Seminar Demo of a Address Service
 *
 * API version: 1.0.0
 * Contact: scni1071@h-ka.de
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	pb "addrServiceRestServer/go/addressServiceProto"
	"encoding/json"
	"net/http"
	"time"
)

var savedAddresses []*pb.Address

func init() {
	pb.MockPopulateAddressBook(&savedAddresses)
}

func AddressesGet(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Access-Control-Allow-Origin", "*")
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)

	// PUSH ALL ELEMENTS AS ARRAY
	for range savedAddresses {
		time.Sleep(5 * time.Millisecond)
	}
	bytes, _ := json.Marshal(savedAddresses)
	w.Write(bytes)
}
