/*
 * Address Service RESTful API
 *
 * This is the RESTful API for the Seminar Demo of a Address Service
 *
 * API version: 1.0.0
 * Contact: scni1071@h-ka.de
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Person struct {

	FamilyName string `json:"familyName"`

	GivenName string `json:"givenName"`
}
