# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: addrService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61\x64\x64rService.proto\"/\n\x06Person\x12\x12\n\nfamilyName\x18\x01 \x01(\t\x12\x11\n\tgivenName\x18\x02 \x01(\t\"b\n\x07\x41\x64\x64ress\x12\x19\n\x08resident\x18\x01 \x01(\x0b\x32\x07.Person\x12\x0e\n\x06street\x18\x02 \x01(\t\x12\r\n\x05house\x18\x03 \x01(\x05\x12\x0f\n\x07zipCode\x18\x04 \x01(\x05\x12\x0c\n\x04\x63ity\x18\x05 \x01(\t\")\n\x0b\x41\x64\x64ressList\x12\x1a\n\x08\x61\x64\x64rList\x18\x01 \x03(\x0b\x32\x08.Address\"\x07\n\x05\x45mpty2\x89\x01\n\x0e\x41\x64\x64ressService\x12$\n\rLookupAddress\x12\x07.Person\x1a\x08.Address\"\x00\x12\'\n\x0fGetAllAddresses\x12\x06.Empty\x1a\x08.Address\"\x00\x30\x01\x12(\n\x0eGetAddressList\x12\x06.Empty\x1a\x0c.AddressList\"\x00\x42\x1cZ\x1aprotos/addressServiceProtob\x06proto3')



_PERSON = DESCRIPTOR.message_types_by_name['Person']
_ADDRESS = DESCRIPTOR.message_types_by_name['Address']
_ADDRESSLIST = DESCRIPTOR.message_types_by_name['AddressList']
_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
Person = _reflection.GeneratedProtocolMessageType('Person', (_message.Message,), {
  'DESCRIPTOR' : _PERSON,
  '__module__' : 'addrService_pb2'
  # @@protoc_insertion_point(class_scope:Person)
  })
_sym_db.RegisterMessage(Person)

Address = _reflection.GeneratedProtocolMessageType('Address', (_message.Message,), {
  'DESCRIPTOR' : _ADDRESS,
  '__module__' : 'addrService_pb2'
  # @@protoc_insertion_point(class_scope:Address)
  })
_sym_db.RegisterMessage(Address)

AddressList = _reflection.GeneratedProtocolMessageType('AddressList', (_message.Message,), {
  'DESCRIPTOR' : _ADDRESSLIST,
  '__module__' : 'addrService_pb2'
  # @@protoc_insertion_point(class_scope:AddressList)
  })
_sym_db.RegisterMessage(AddressList)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'addrService_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

_ADDRESSSERVICE = DESCRIPTOR.services_by_name['AddressService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\032protos/addressServiceProto'
  _PERSON._serialized_start=21
  _PERSON._serialized_end=68
  _ADDRESS._serialized_start=70
  _ADDRESS._serialized_end=168
  _ADDRESSLIST._serialized_start=170
  _ADDRESSLIST._serialized_end=211
  _EMPTY._serialized_start=213
  _EMPTY._serialized_end=220
  _ADDRESSSERVICE._serialized_start=223
  _ADDRESSSERVICE._serialized_end=360
# @@protoc_insertion_point(module_scope)
