# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import addrService_pb2 as addrService__pb2


class AddressServiceStub(object):
    """Definition of the service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LookupAddress = channel.unary_unary(
                '/AddressService/LookupAddress',
                request_serializer=addrService__pb2.Person.SerializeToString,
                response_deserializer=addrService__pb2.Address.FromString,
                )
        self.GetAllAddresses = channel.unary_stream(
                '/AddressService/GetAllAddresses',
                request_serializer=addrService__pb2.Empty.SerializeToString,
                response_deserializer=addrService__pb2.Address.FromString,
                )
        self.GetAddressList = channel.unary_unary(
                '/AddressService/GetAddressList',
                request_serializer=addrService__pb2.Empty.SerializeToString,
                response_deserializer=addrService__pb2.AddressList.FromString,
                )


class AddressServiceServicer(object):
    """Definition of the service
    """

    def LookupAddress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllAddresses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAddressList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AddressServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LookupAddress': grpc.unary_unary_rpc_method_handler(
                    servicer.LookupAddress,
                    request_deserializer=addrService__pb2.Person.FromString,
                    response_serializer=addrService__pb2.Address.SerializeToString,
            ),
            'GetAllAddresses': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAllAddresses,
                    request_deserializer=addrService__pb2.Empty.FromString,
                    response_serializer=addrService__pb2.Address.SerializeToString,
            ),
            'GetAddressList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAddressList,
                    request_deserializer=addrService__pb2.Empty.FromString,
                    response_serializer=addrService__pb2.AddressList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AddressService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AddressService(object):
    """Definition of the service
    """

    @staticmethod
    def LookupAddress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AddressService/LookupAddress',
            addrService__pb2.Person.SerializeToString,
            addrService__pb2.Address.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAllAddresses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/AddressService/GetAllAddresses',
            addrService__pb2.Empty.SerializeToString,
            addrService__pb2.Address.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAddressList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AddressService/GetAddressList',
            addrService__pb2.Empty.SerializeToString,
            addrService__pb2.AddressList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
